name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          # Write key with proper line endings
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 8.130.124.23 >> ~/.ssh/known_hosts
          # Debug steps
          echo "SSH directory contents:"
          ls -la ~/.ssh/
          echo "First and last line of key file (to verify format):"
          head -n 1 ~/.ssh/id_rsa
          tail -n 1 ~/.ssh/id_rsa
          echo "Testing SSH connection..."
          ssh -vvv -o StrictHostKeyChecking=no root@8.130.124.23 'echo "SSH test"'

      - name: Deploy to server
        run: |
          scp -r dist/* root@8.130.124.23:/var/www/lyxhai.com/
